
import { CheatKeyCategoryData, ComboTip, CheatKey } from '../../types';

export const comboTips: ComboTip[] = [
    { id: 'real_survivor', title: '리얼 생존자 / Real Survivor', description: '산전수전 다 겪은 처절하고 강인한 생존자 (추천)', keys: ['char_ultimate_survivor', 'fashion_survivor_tank', 'detail_sweat_grime', 'art_raw_photo'] },
    { id: 'epic_fantasy', title: '에픽 판타지 / Epic Fantasy', description: '웅장하고 서사적인 판타지 장면', keys: ['genre_high_fantasy', 'detail_insanely_detailed', 'lighting_dramatic_rim_lighting', 'comp_extreme_long_shot'] },
    { id: 'cyberpunk_noir', title: '사이버펑크 느와르 / Cyberpunk Noir', description: '어둡고 비 오는 미래 도시의 뒷골목', keys: ['genre_cyberpunk', 'genre_noir_detective', 'weather_torrential_downpour', 'lighting_flickering_streetlights'] },
    { id: 'ghibli_anime', title: '지브리 애니메이션 / Ghibli Anime Style', description: '따뜻하고 몽환적인 애니메이션', keys: ['art_style_ghibli', 'lighting_golden_hour', 'weather_magical_pollen'] },
    { id: 'dramatic_portrait', title: '인물 클로즈업 / Dramatic Portrait', description: '감정이 살아있는 인물 중심의 샷', keys: ['comp_close_up_shot', 'lighting_dramatic_soft_lighting', 'texture_lifelike_skin_texture', 'expr_tearful'] },
    { id: 'lifelike_texture', title: '생동감 있는 질감 / Lifelike Texture', description: '피부, 털가죽 등 살아있는 듯한 질감', keys: ['detail_hyperrealistic', 'texture_lifelike_skin_texture', 'texture_detailed_pores', 'texture_hyperrealistic_fur_texture'] },
    { id: 'glamorous_fit', title: '글래머러스 핏 / Glamorous Fit', description: '옷을 입어도 드러나는 확실한 볼륨감', keys: ['body_bombshell', 'fashion_corset', 'detail_clothing_fit', 'fashion_sweetheart'] },
];

export const cheatKeysData: CheatKeyCategoryData = {
    "Character Type (인물 유형)": [
        { id: 'char_ultimate_survivor', label: '최강 생존자', prompt: 'a hardened female survivor, athletic build, intense survival instinct, gritty realism, not a 3D render, real person', description: '산전수전 다 겪은 강인한 여성 생존자 (라라 크로프트/엘리 스타일)' },
        { id: 'char_rogue_agent', label: '로그 에이전트', prompt: 'a former agent turned rogue, wearing tactical casual gear, weathered face, scars, realistic', description: '조직을 떠나 홀로 생존하는 전직 요원, 현실적인 묘사' },
        { id: 'char_urban_guerrilla', label: '도시 게릴라', prompt: 'a civilian resistance fighter, desperate expression, holding a weapon, dirty face', description: '절박한 표정의 도심 저항군/게릴라' },
        { id: 'char_fugitive', label: '도망자', prompt: 'a fugitive on the run, disheveled hair, fearful but determined eyes, realistic photography', description: '쫓기는 도망자, 헝클어진 머리와 결의에 찬 눈빛' },

        // Previous keys kept for variety
        { id: 'char_cyber_runner', label: '사이버펑크 용병', prompt: 'a cyberpunk edgerunner with cybernetic implants', description: '사이버네틱 이식물을 가진 사이버펑크 용병' },
        { id: 'char_noir_detective', label: '느와르 탐정', prompt: 'a gritty noir detective smoking a cigarette', description: '담배를 문 거친 느와르 탐정' },
        { id: 'char_kpop_idol', label: 'K-Pop 아이돌', prompt: 'a trendy K-Pop idol with colorful dyed hair', description: '화려한 염색 머리의 트렌디한 K-Pop 아이돌' },
        { id: 'char_jazz_singer', label: '재즈 싱어', prompt: 'a charismatic female jazz singer', description: '카리스마 있는 여성 재즈 싱어' },
        { id: 'char_samurai', label: '로닌 사무라이', prompt: 'a wandering Ronin Samurai with a scarred face', description: '흉터가 있는 떠돌이 로닌 사무라이' },
    ],
    "Body Type & Appearance (체형 & 외형)": [
        // Female focused
        { id: 'body_slim_glamour', label: '슬림 글래머 (Slim Glamour)', prompt: 'hourglass figure, slim waist, feminine curves, toned physique, glamorous fit, elegant silhouette', description: '검열을 피하면서도 볼륨감과 날씬함을 동시에 잡는 황금 밸런스 (강력 추천)' },
        { id: 'body_bombshell', label: '핀업걸 / 밤셸', prompt: 'bombshell figure, pin-up style physique, buxom, heavy chest, deep curves, hourglass ratio', description: '50년대 핀업걸 스타일의 과장되고 매혹적인 곡선미 (주의: 체격이 커질 수 있음)' },
        { id: 'body_voluptuous', label: '풍만한 글래머', prompt: 'voluptuous figure, full-figured, ample curves, heavy chest, glamorous physique', description: '풍만하고 볼륨감 있는 글래머러스한 체형, 상체 볼륨 강조' },
        { id: 'body_hourglass', label: '모래시계형', prompt: 'hourglass figure, curvaceous physique, feminine silhouette, wide hips', description: '균형 잡힌 굴곡이 있는 모래시계형 체형, 넓은 골반' },
        { id: 'body_athletic_f', label: '운동형 / 탄탄한', prompt: 'athletic physique, toned muscles, fit body, abs, healthy look', description: '운동으로 다져진 탄탄하고 건강한 몸매' },
        { id: 'body_slender', label: '슬렌더 / 슬림', prompt: 'slender build, slim figure, delicate frame, elegant posture', description: '가냘프고 슬림한 체형, 우아한 라인' },
        { id: 'body_model', label: '모델 / 장신', prompt: 'tall and statuesque, model-like proportions, long legs', description: '키가 크고 비율이 좋은 모델 같은 체형' },
        { id: 'body_petite', label: '아담한 / 쁘띠', prompt: 'petite frame, small stature, cute proportions', description: '아담하고 작은 체구, 귀여운 비율' },

        // Male / General
        { id: 'body_muscular', label: '근육질 / 찢어진 근육', prompt: 'heavily muscular, ripped physique, broad shoulders, vascularity, bodybuilder', description: '근육질의 강인한 체형, 넓은 어깨' },
        { id: 'body_lean', label: '마른 체형 / 호리호리한', prompt: 'lean build, lanky, sharp features, skinny', description: '군살 없이 마른 체형, 날카로운 인상' },
        { id: 'body_stocky', label: '다부진 체형', prompt: 'stocky build, heavy set, thick neck, strongman physique', description: '다부지고 묵직한 체형' },
        { id: 'body_chiseled', label: '조각 같은 얼굴', prompt: 'chiseled jawline, high cheekbones, handsome features', description: '조각 같은 턱선과 얼굴 윤곽' },
    ],
    "Hairstyle (헤어스타일)": [
        { id: 'hair_messy_bun', label: '흐트러진 똥머리', prompt: 'messy bun with loose strands framing the face, practical updo', description: '느슨하게 묶은 똥머리, 잔머리가 흘러내린 자연스러운 스타일 (생존자/일상)' },
        { id: 'hair_ponytail', label: '하이 포니테일', prompt: 'high tactical ponytail, sleek pulled back hair', description: '활동적인 높게 묶은 포니테일 (라라 크로프트 스타일)' },
        { id: 'hair_wet_matted', label: '젖은 / 엉킨 머리', prompt: 'wet matted hair, sweat-drenched hair, heavy texture', description: '비나 땀에 젖어 뭉친 머리카락 (리얼리티 강조)' },
        { id: 'hair_windblown', label: '바람에 날리는 머리', prompt: 'windblown hair, hair flowing in the wind, dynamic hair motion', description: '바람에 흩날리는 역동적인 머리카락' },
        { id: 'hair_braid', label: '땋은 머리', prompt: 'long single french braid, loose braid', description: '길게 땋은 머리, 청순하거나 전사 같은 느낌' },
        { id: 'hair_bob_wavy', label: '웨이브 단발', prompt: 'short wavy bob cut, platinum blonde wavy bob, vintage style', description: '웨이브가 있는 단발 보브컷 (고전적/우아함)' },
        { id: 'hair_pixie', label: '픽시 컷', prompt: 'short textured pixie cut, edgy haircut', description: '짧고 텍스처가 살아있는 픽시컷 (현대적/시크함)' },
        { id: 'hair_long_straight', label: '긴 생머리', prompt: 'long straight hair down to waist, silky texture', description: '허리까지 오는 긴 생머리' },
        { id: 'hair_bangs', label: '앞머리 있음', prompt: 'hair with bangs, wispy fringe', description: '앞머리가 있는 스타일' },
        { id: 'hair_undercut', label: '언더컷', prompt: 'undercut hairstyle, shaved sides', description: '옆머리를 민 언더컷 (펑크/사이버펑크)' },
        { id: 'hair_buzz_cut', label: '반삭 / 버즈컷', prompt: 'military buzz cut, shaved head', description: '군인 스타일의 짧은 반삭' },
        { id: 'hair_dye', label: '화려한 염색', prompt: 'colorful dyed hair, neon highlights', description: '화려한 염색 머리, 네온 하이라이트' },
    ],
    "Fashion & Costume (패션 & 의상)": [
        // Real Survival Gear
        { id: 'fashion_survivor_tank', label: '생존자 탱크탑', prompt: 'wearing a dirty sweat-stained tank top, worn cargo shorts, leather belt with gun holster, combat boots, realistic texture', description: '땀과 흙으로 얼룩진 민소매와 반바지, 홀스터 (생존자 정석)' },
        { id: 'fashion_tactical_civilian', label: '전술 민간인', prompt: 'wearing torn jeans, dirty t-shirt, tactical vest, fingerless gloves, drop-leg holster', description: '청바지/티셔츠에 전술 조끼와 홀스터를 착용한 현실적 생존 룩' },
        { id: 'fashion_distressed_basics', label: '낡은 기본 의류', prompt: 'wearing heavily distressed clothes, holes in t-shirt, mud stains, worn-out denim', description: '구멍 나고 진흙 묻은 낡은 기본 의류' },

        // Footwear & Full Body Tricks
        { id: 'footwear_heavy_boots', label: '무거운 전투화 (전신 유도)', prompt: 'wearing heavy combat boots, visible shoes, full body view', description: '투박한 군화를 묘사하여 자연스럽게 전신 샷을 유도' },
        { id: 'footwear_tactical_boots', label: '전술 부츠 (전신 유도)', prompt: 'wearing black tactical boots, visible footwear', description: '날렵한 전술 부츠 착용' },
        { id: 'footwear_thigh_high', label: '싸이하이 부츠 (전신 유도)', prompt: 'wearing leather thigh-high boots, showing full legs', description: '허벅지까지 오는 롱부츠 (툼 레이더/여전사 스타일)' },
        { id: 'footwear_worn_sneakers', label: '낡은 스니커즈 (전신 유도)', prompt: 'wearing worn-out converse sneakers, visible shoes', description: '낡은 스니커즈 (캐주얼/생존자)' },

        // Others
        { id: 'fashion_corset', label: '구조적 코르셋 / 뷔스티에', prompt: 'wearing a structured corset bustier, push-up effect, cinched waist, accentuated bust', description: '라인을 확실하게 잡아주는 코르셋/뷔스티에, 볼륨 업 효과 (추천)' },
        { id: 'fashion_sweetheart', label: '스윗하트 넥라인', prompt: 'sweetheart neckline, fitted bodice, emphasizing upper body form', description: '가슴 라인을 하트 모양으로 감싸는 넥라인, 볼륨 강조' },
        { id: 'fashion_form_fitting', label: '타이트 핏', prompt: 'form-fitting outfit, skin-tight clothes, clinging to body, accentuated curves', description: '몸매가 드러나는 타이트한 핏, 굴곡 강조' },
        { id: 'fashion_plunging_neckline', label: '깊게 파인 넥라인', prompt: 'plunging V-neckline, deep neckline, revealing decolletage', description: '깊게 파인 넥라인, 쇄골과 가슴 라인 강조' },
        { id: 'fashion_off_shoulder', label: '오프숄더', prompt: 'off-shoulder top, exposed collarbones and shoulders', description: '어깨와 쇄골이 드러나는 오프숄더' },
        { id: 'fashion_ribbed_knit', label: '골지 니트', prompt: 'wearing a tight ribbed knit sweater, fabric stretching', description: '굴곡을 따라 늘어나는 골지 니트 소재' },
        { id: 'fashion_latex', label: '광택 라텍스 / 스판덱스', prompt: 'wearing shiny latex bodysuit, reflective fabric, vacuum fit', description: '반짝이는 라텍스/스판덱스, 진공 핏' },
        { id: 'fashion_techwear', label: '퓨처리스틱 테크웨어', prompt: 'wearing futuristic techwear with straps and buckles', description: '스트랩과 버클이 달린 미래지향적 테크웨어' },
        { id: 'fashion_plate_armor', label: '화려한 판금 갑옷', prompt: 'wearing intricate gold-filigreed plate armor', description: '정교한 금세공이 들어간 플레이트 아머' },
        { id: 'fashion_streetwear', label: '하이프비스트 스트릿', prompt: 'wearing oversized hypebeast streetwear and sneakers', description: '오버사이즈 하이프비스트 스트릿웨어와 스니커즈' },
        { id: 'fashion_victorian', label: '빅토리안 고딕', prompt: 'wearing an elegant Victorian gothic gown with lace', description: '레이스가 달린 우아한 빅토리안 고딕 드레스' },

        // --- Spicy Bottoms (섹시 하의) ---
        { id: 'fashion_micro_mini', label: '마이크로 미니 스커트', prompt: 'wearing a Micro Mini Skirt', description: '군더더기 없이 다리 라인만 강조하는 초미니 스커트 (원단/데님)' },
        { id: 'fashion_low_rise_shorts', label: '로우라이즈 핫팬츠 (배꼽 노출)', prompt: 'wearing Low-rise Micro Hot Pants (Navel visible)', description: '골반에 걸쳐 입어 배꼽과 허리 라인이 완전히 드러나는 과감한 숏팬츠' },
        { id: 'fashion_yoga_booty', label: '요가 부티 숏츠 (초밀착)', prompt: 'wearing Ultra-short Yoga Booty Shorts', description: '레깅스 재질인데 기장은 팬티 수준으로 짧은 운동복 스타일' },
        { id: 'fashion_checkered_skirt', label: '체크무늬 스쿨룩 스커트', prompt: 'wearing a Checkered Micro Mini Skirt', description: '테니스 스커트에 체크 패턴을 넣어 더 영하고 발랄한 느낌' },
        { id: 'fashion_wrap_slit', label: '옆트임 랩 스커트', prompt: 'wearing a Micro Wrap Skirt with Side Slit', description: '옆부분이 트여 있어 움직일 때마다 다리가 보이는 아슬아슬한 디자인' },
        { id: 'fashion_ruffle_mini', label: '레이어드 러플 스커트', prompt: 'wearing a Layered Ruffle Mini Skirt', description: '캉캉치마처럼 짧은 주름이 층층이 겹쳐진 귀엽고 섹시한 스타일' },

        // --- Spicy Tops (섹시 상의) ---
        { id: 'fashion_micro_tube', label: '마이크로 튜브탑', prompt: 'wearing a Micro Tube Top', description: '어깨끈 없이 가슴만 가리는 가장 심플하고 섹시한 아이템' },
        { id: 'fashion_backless_halter', label: '백리스 홀터넥', prompt: 'wearing a Backless Halter-neck Top', description: '앞은 목을 감싸지만 등은 시원하게 파인 반전 매력' },
        { id: 'fashion_see_through_blouse', label: '시스루 블라우스 (란제리룩)', prompt: 'wearing a Sheer See-through Blouse', description: '속옷이 은은하게 비치는 얇은 소재의 블라우스/셔츠' },
        { id: 'fashion_deep_v_bodysuit', label: '딥 V넥 바디수트', prompt: 'wearing a Deep V-neck Bodysuit', description: '상의가 절대 말려 올라가지 않고 허리 라인을 꽉 잡아주는 수트' },
        { id: 'fashion_satin_cami', label: '새틴 슬립 캐미솔', prompt: 'wearing a Satin Slip Camisole', description: '광택이 흐르는 실크 소재의 얇은 끈나시 (고급스러운 섹시함)' },
        { id: 'fashion_cross_strap', label: '크로스 스트랩 탑', prompt: 'wearing a Criss-cross Strap Top', description: '가슴이나 허리에 X자 끈 디테일이 들어간 힙한 스타일' },
    ],
    "Expression & Action (표정 & 행동)": [
        // Performance / Stage
        { id: 'pose_singing', label: '노래하는 모습', prompt: 'performing on stage, singing into a vintage microphone, holding mic stand, dynamic performance', description: '무대 위에서 마이크를 잡고 열창하는 모습' },
        { id: 'pose_facing_camera', label: '카메라 정면 응시', prompt: 'facing the camera, front view, symmetrical composition, looking at viewer', description: '정면을 바라보는 구도' },

        // High Intensity Actions
        { id: 'pose_running_gun', label: '총 들고 달리기', prompt: 'sprinting while holding a handgun, intense focus, fleeing from danger, dynamic motion blur', description: '총을 들고 전력 질주하는 긴박한 모습' },
        { id: 'pose_aiming_intense', label: '조준 (강렬한)', prompt: 'aiming a weapon with intense focus, gritted teeth, ready to fire, muscles tensed', description: '치열한 표정으로 조준하는 자세' },
        { id: 'pose_crawling', label: '기어가기 / 엎드리기', prompt: 'crawling on the ground, prone position, hiding, covered in dirt', description: '바닥에 기어가거나 엎드린 자세' },

        // Emotions / Expressions (표정)
        { id: 'expr_desperate', label: '절박함 / 공포', prompt: 'expression of pure desperation, fear in eyes, heavy breathing, sweating', description: '절박함, 공포, 거친 숨' },
        { id: 'expr_fierce', label: '맹렬한 결의', prompt: 'fierce determined look, intense stare, survival instinct, adrenaline', description: '살아남겠다는 강한 의지, 맹렬한 눈빛' },
        { id: 'expr_tearful', label: '눈물 / 우는', prompt: 'tears streaming down face, red puffy eyes, expression of deep sorrow, crying, wet cheeks', description: '흐르는 눈물, 붉어진 눈시울, 깊은 슬픔' },
        { id: 'expr_rage', label: '분노 / 절규', prompt: 'screaming in rage, mouth wide open, veins popping on neck, intense anger, furious expression', description: '격렬한 분노, 절규, 튀어나온 핏줄' },
        { id: 'expr_gentle_smile', label: '온화한 미소', prompt: 'gentle warm smile, soft eyes, happy expression, heartwarming', description: '부드럽고 따뜻한 미소, 온화함' },
        { id: 'expr_smirk', label: '거만한 미소', prompt: 'arrogant smirk, one eyebrow raised, confident expression, mischievous look', description: '거만한 미소, 한쪽 눈썹 치켜올림, 자신감' },
        { id: 'expr_ecstatic', label: '환희 / 박장대소', prompt: 'laughing hysterically, head thrown back, closed eyes, expression of pure joy', description: '고개를 젖히고 박장대소, 환희' },
        { id: 'expr_seductive', label: '유혹적인 눈빛', prompt: 'seductive gaze, biting lip, heavy eyelids, alluring expression', description: '유혹적인 눈빛, 입술 깨물기' },

        // Actions / Poses (행동/포즈)
        { id: 'pose_looking_back', label: '뒤돌아보기', prompt: 'looking back over shoulder, turning head, mystery', description: '어깨 너머로 뒤돌아보는 모습' },
        { id: 'pose_falling', label: '추락 / 떨어짐', prompt: 'falling through the air, flailing arms, dynamic perspective, wind blowing hair', description: '공중에서 추락하는 모습, 허우적거림' },
        { id: 'pose_kneeling', label: '무릎 꿇기 (패배)', prompt: 'kneeling on the ground, head bowed, defeated posture, rain falling', description: '바닥에 무릎 꿇음, 고개 숙인 패배감' },
        { id: 'pose_face_palm', label: '얼굴 감싸기', prompt: 'covering face with hands, despair, hiding face', description: '양손으로 얼굴을 감싸 쥔 절망' },
        { id: 'pose_reaching', label: '손 뻗기', prompt: 'reaching out hand towards camera, desperate grasping gesture, perspective distortion', description: '카메라를 향해 절박하게 뻗은 손' },
        { id: 'pose_silhouette', label: '실루엣', prompt: 'silhouette against light, mysterious figure, backlighting', description: '역광 실루엣, 신비로운 분위기' },
        { id: 'pose_arch_back', label: '등 젖히기', prompt: 'arching back slightly, accentuating silhouette, dynamic pose', description: '등을 살짝 젖혀 실루엣을 강조하는 포즈' },
    ],
    "Subject Details / Material (피사체 디테일 / 재질)": [
        // Survival Realism
        { id: 'detail_sweat_grime', label: '심한 땀 & 때', prompt: 'heavy sweat dripping, skin covered in grime and mud, wet hair, oily skin texture', description: '흐르는 땀, 진흙, 젖은 머리 (리얼함의 핵심)' },
        { id: 'detail_muddy_skin', label: '진흙 / 더러운 피부', prompt: 'mud-caked skin, dirty face, realistic survival accumulation', description: '진흙이 묻어 굳은 피부, 더러워진 얼굴' },
        { id: 'detail_scars_bruises', label: '흉터 & 멍', prompt: 'realistic scars, fresh cuts, bruises on skin, battle damage', description: '현실적인 흉터, 베인 상처, 멍' },

        { id: 'detail_clothing_fit', label: '타이트 핏 / 텐션', prompt: 'clothing straining against curves, tight fit, fabric tension', description: '옷이 몸매에 꽉 끼어 생기는 주름과 핏' },
        { id: 'detail_clothing_physics', label: '옷감의 물리적 움직임', prompt: 'detailed clothing physics, fabric draping naturally', description: '옷감의 자연스러운 물리적 움직임' },
        { id: 'material_chrome', label: '광택 크롬', prompt: 'made of polished chrome', description: '광택 있는 크롬' },
        { id: 'material_brass', label: '무광 황동', prompt: 'made of brushed brass', description: '결이 살아있는 황동' },
        { id: 'material_rusted_iron', label: '녹슨 철', prompt: 'made of rusted corrugated iron', description: '녹슨 양철' },
        { id: 'material_iridescent', label: '오색찬란한 금속', prompt: 'made of iridescent metal', description: '보는 각도에 따라 색이 변하는 금속' },
        { id: 'material_damascus', label: '다마스쿠스 강철', prompt: 'made of Damascus steel pattern', description: '다마스쿠스 강철 패턴' },
        { id: 'material_velvet', label: '찢어진 벨벳', prompt: 'torn and frayed velvet', description: '찢어지고 해진 벨벳' },
        { id: 'material_leather', label: '오래된 가죽', prompt: 'heavy weathered leather', description: '오래된 가죽' },
        { id: 'material_silk', label: '흩날리는 실크', prompt: 'delicate flowing silk', description: '부드럽게 흩날리는 실크' },
        { id: 'material_translucent_skin', label: '반투명 피부', prompt: 'translucent skin', description: '반투명한 피부' },
    ],
    "Multi-Character & Crowd (다중 인물 & 군중)": [
        { id: 'multi_squad_backup', label: '팀 백업 (후방)', prompt: 'flanked by two armed squad members standing in the background, tactical team formation, depth of field', description: '주인공 뒤에 무장한 팀원 2명이 서 있는 구도 (호위)' },
        { id: 'multi_triangular', label: '삼각형 대형', prompt: 'triangular composition, main character in front center, two support characters behind left and right', description: '앞에 주인공, 뒤에 2명으로 이루어진 삼각형 구도' },
        { id: 'multi_distinct', label: '개성 있는 캐릭터들', prompt: 'distinct characters, no clones, unique individual features for every person, variation in faces and clothing', description: '얼굴 복제(클론 현상) 방지, 각 인물의 개성 분리' },
        { id: 'multi_contrast_duo', label: '대조적인 듀오', prompt: 'two characters with contrasting styles, visual juxtaposition, opposing aesthetics (e.g. formal vs casual)', description: '서로 정반대 스타일의 두 인물 배치' },
        { id: 'multi_squad', label: '팀 / 분대', prompt: 'group of distinct characters, team squad, diverse outfits within same theme, avengers style group shot', description: '어벤져스처럼 각기 다른 복장의 팀원 구도' },
        { id: 'multi_crowd_detail', label: '군중 디테일', prompt: 'bustling crowd in background, detailed background characters, diverse crowd, sharp focus on background faces', description: '배경 군중들도 흐릿하지 않고 디테일하게 묘사' },
        { id: 'multi_interaction', label: '역동적 상호작용', prompt: 'characters interacting with each other, talking, fighting, embracing, dynamic relationship', description: '인물 간의 상호작용(대화, 전투, 포옹 등)' },
    ],
    "Director's Style": [
        { id: 'director_wong_kar_wai', label: 'Wong Kar-wai', prompt: '[감독/스타일: in the moody, neon-soaked aesthetic of Wong Kar-wai], [카메라/구도: Shot on Arriflex 35BL camera with vintage Cooke Speed Panchro 75mm lens, Aspect Ratio 2.35:1, Cinemascope framing], [필름: Kodak Vision3 500T color negative film, heavy film grain, halation effect on neon lights], [효과: slight motion blur, step-printing effect, dreamy atmosphere], [조명: warm directional lighting on face, golden hour glow]', description: '특유의 색감과 분위기 깡패, 감성 사진 전용 (16:9 추천)', aspectRatioGroup: '16:9' },
        { id: 'director_blomkamp', label: 'Neill Blomkamp', prompt: 'in the raw, documentary sci-fi style of Neill Blomkamp. --ar 16:9', description: '날것의 현실감, SF 다큐멘터리, 핸드헬드. 최적 종횡비: 16:9', aspectRatioGroup: '16:9' },
        { id: 'director_villeneuve', label: 'Denis Villeneuve', prompt: 'in the atmospheric, texture-rich style of Denis Villeneuve. --ar 21:9', description: '압도적인 스케일, 분위기를 지배하는 미장센. 최적 종횡비: 21:9', aspectRatioGroup: '16:9' },
        { id: 'director_nolan', label: 'Christopher Nolan', prompt: 'in the grounded, epic-scale style of Christopher Nolan. --ar 16:9', description: '현실적이고 장대한 스케일, 묵직한 서사. 최적 종횡비: 16:9', aspectRatioGroup: '16:9' },
        { id: 'director_anderson', label: 'Wes Anderson', prompt: 'in the meticulously symmetrical, pastel-colored style of Wes Anderson. --ar 4:3', description: '완벽한 대칭 구도, 동화 같은 색감, 인형의 집 미장센. 최적 종횡비: 4:3', aspectRatioGroup: '4:3' },
        { id: 'director_cuaron', label: 'Alfonso Cuarón', prompt: 'in the visceral, immersive long-take style of Alfonso Cuarón. --ar 16:9', description: '끊기지 않는 롱테이크(Long Take), 유려한 핸드헬드, 관객을 압도하는 현장감과 몰입감. 최적 종횡비: 16:9', aspectRatioGroup: '16:9' },
        { id: 'director_chazelle', label: 'Damien Chazelle', prompt: 'in the energetic, rhythmic, vertical cinema style of Damien Chazelle. --ar 9:16', description: '음악적 리듬감, 폭발적인 에너지, 인물의 감정을 따라가는 역동적인 카메라 워크. 최적 종횡비: 9:16', aspectRatioGroup: '9:16' },
        { id: 'director_tarantino', label: 'Quentin Tarantino', prompt: 'in the stylish, retro-cool, anamorphic widescreen style of Quentin Tarantino. --ar 2.39:1', description: '레트로 감성, 스타일리시한 폭력, 장르 영화(서부극, B급 영화 등)에 대한 오마주. 최적 종횡비: 2.39:1', aspectRatioGroup: '16:9' },
        { id: 'director_refn', label: 'Nicolas Winding Refn', prompt: 'in the neon-drenched, synthwave-noir style of Nicolas Winding Refn. --ar 2.39:1', description: '네온-누아르, 극단적인 색채 대비(주로 네온 핑크/블루와 블랙), 미니멀하고 정적인 구도. 최적 종횡비: 2.39:1', aspectRatioGroup: '16:9' },
        { id: 'director_deltoro', label: 'Guillermo del Toro', prompt: 'in the dark, gothic fairy-tale style of Guillermo del Toro. --ar 1.85:1', description: '다크 판타지, 고딕 로맨스, 정교하고 아름다운 괴물 디자인, 풍부한 디테일 (주로 호박색/청록색 톤). 최적 종횡비: 1.85:1', aspectRatioGroup: '16:9' },
        { id: 'director_fincher', label: 'David Fincher', prompt: 'in the cold, desaturated, meticulously controlled style of David Fincher. --ar 2.39:1', description: '차갑고 어두운 톤, 절제된 색감(주로 녹색/노란색), 완벽하게 통제된 미장센, 그림자를 활용한 스릴러. 최적 종횡비: 2.39:1', aspectRatioGroup: '16:9' },
    ],
    "Camera & Lens": [
        { id: 'lens_cooke_panchro', label: 'Cooke Speed Panchro', prompt: 'Shot on vintage Cooke Speed Panchro lenses, creamy bokeh, shallow depth of field', description: '낭만적이고 몽환적인 스타일', aspectRatioGroup: '16:9' },
        { id: 'cam_sony_a7_iv', label: '소니 a7 IV (브이로그/유튜브)', prompt: 'Shot on Sony a7 IV with Sigma 16-28mm F2.8 DG DN', description: '풀프레임 센서와 광각 줌 렌즈를 통해 시원한 공간감을 제공하며, F2.8 조리개는 피사체와 배경을 효과적으로 분리시켜 줍니다. (9:16 세로 영상에 최적화)', aspectRatioGroup: '9:16' },
        { id: 'cam_bmpcc_4k', label: 'BMPCC 4K (시네마틱)', prompt: 'Shot on Blackmagic Pocket Cinema Camera 4K with Panasonic Leica 12-60mm f/2.8-4.0', description: '압축되지 않은 RAW 녹화를 지원하여 후반 색 보정에서 월등한 관용도를 보여주는 시네마 카메라입니다. (9:16 세로 영상에 최적화)', aspectRatioGroup: '9:16' },
        { id: 'cam_iphone_15_pro', label: '아이폰 15 Pro (모바일)', prompt: 'Shot on iPhone 15 Pro, cinematic mode', description: '스마트폰 시네마틱 모드로 촬영된 영상미. 자연스러운 심도 표현과 안정적인 영상미를 제공합니다. (9:16 세로 영상에 최적화)', aspectRatioGroup: '9:16' },
        { id: 'cam_canon_c70', label: '캐논 C70 (인물 중심)', prompt: 'Shot on Canon EOS C70 with Canon RF 24-70mm F2.8 L IS USM', description: '정확하고 부드러운 피부 톤 표현으로 유명하며, 다용도로 활용하기 좋은 조합입니다. (16:9 가로 영상에 최적화)', aspectRatioGroup: '16:9' },
        { id: 'cam_arri_alexa_lf', label: 'ARRI 알렉사 (헐리우드 표준)', prompt: 'Shot on ARRI Alexa Mini LF with Atlas Orion Anamorphic lens', description: '영화 산업의 표준 조합. 탁월한 다이내믹 레인지와 압도적인 시네마틱 영상미를 구현합니다. (16:9 시네마틱 가로 영상에 최적화)', aspectRatioGroup: '16:9' },
        { id: 'cam_bmpcc_6k', label: 'BMPCC 6K Pro (영화적 감성)', prompt: 'Shot on Blackmagic Pocket Cinema Camera 6K Pro with Sigma 18-35mm F1.8 Art', description: 'Super 35mm 센서와 F1.8의 매우 밝은 조리개로 영화적인 얕은 심도 표현에 극도로 유리합니다. (16:9 시네마틱 가로 영상에 최적화)', aspectRatioGroup: '16:9' },
        { id: 'cam_sony_fx3', label: '소니 FX3 (감성 영상)', prompt: 'Shot on Sony FX3 with Sony FE 50mm F1.2 GM lens', description: '컴팩트 시네마 카메라와 밝은 단렌즈의 조합. 인물 중심의 감성적인 영상에 탁월한 성능을 보입니다. (16:9 가로 영상에 최적화)', aspectRatioGroup: '16:9' },
        { id: 'cam_panasonic_gh6', label: '파나소닉 GH6 (아나모픽)', prompt: 'Shot on Panasonic Lumix GH6 with Sirui 35mm T2.9 1.6x Anamorphic lens', description: '4:3 비율의 센서를 모두 활용하는 아나모픽 촬영에 특화되어 독특하고 예술적인 영상을 만들 수 있습니다. (4:3 비율에 최적화)', aspectRatioGroup: '4:3' },
        { id: 'cam_red_komodo', label: 'RED 코모도 (CF/뮤비)', prompt: 'Shot on RED Komodo 6K with Cooke Anamorphic/i Full Frame Plus lens', description: '방대한 영상 정보를 담는 R3D RAW와 특유의 부드럽고 따뜻한 Cooke Look의 조합입니다. (4:3 비율에 최적화)', aspectRatioGroup: '4:3' },
        { id: 'art_splash_art', label: '스플래시 아트', prompt: 'in the style of splash art', description: '스플래시 아트 스타일' },
        { id: 'art_graphic_novel', label: '그래픽 노블', prompt: 'in the style of a graphic novel', description: '그래픽 노블 스타일' },
        { id: 'art_style_ghibli', label: '지브리 스타일', prompt: 'in the style of Studio Ghibli, anime screencap', description: '스튜디오 지브리 애니메이션 스타일' },
        { id: 'art_deco', label: '아르데코', prompt: 'in the style of Art Deco', description: '아르데코 스타일' },
        { id: 'art_cel_shading', label: '셀 셰이딩', prompt: 'cel shading style', description: '셀 셰이딩 스타일' },
        { id: 'art_polaroid', label: '빈티지 폴라로이드', prompt: 'vintage Polaroid photo', description: '빈티지 폴라로이드 사진 스타일' },
        { id: 'art_daguerreotype', label: '다게레오타입 (은판)', prompt: 'in the style of a Daguerreotype', description: '다게레오타입(은판 사진) 스타일' },
        { id: 'art_technicolor', label: '테크니컬러 (고전 영화)', prompt: 'in the style of a Technicolor film', description: '테크니컬러 필름 스타일' },
        { id: 'art_bleach_bypass', label: '블리치 바이패스', prompt: 'bleach bypass effect', description: '블리치 바이패스 효과' },
    ],
    "만화/애니메이션 스타일 (Manga/Animation Style)": [
        { id: 'manga_classic_anime', label: 'Classic Anime Style', prompt: 'anime-style illustration', description: '전통적인 일본 애니 기본 스타일 (클린 라인, 채색 뚜렷)' },
        { id: 'manga_style', label: 'Manga Style', prompt: 'manga-style, Japanese manga aesthetic', description: '흑백선 강조, 먹선・톤・배경 간결' },
        { id: 'manga_shonen', label: 'Shonen Manga Style', prompt: 'shonen manga style, dynamic action composition', description: '<드래곤볼>, <원피스>류 — 액션 중심, 과장된 표정과 구도' },
        { id: 'manga_seinen', label: 'Seinen Manga Style', prompt: 'seinen manga style, cinematic shadows, detailed ink', description: '<베르세르크>, <바가본드>처럼 성인향 무협, 사실적 명암' },
        { id: 'manga_samurai', label: 'Samurai Anime Style', prompt: 'samurai anime style, Edo period setting', description: '일본 무사, 검객 중심 — 동양풍 복식, 잔잔한 붓질 질감' },
        { id: 'manga_ghibli', label: 'Ghibli Style', prompt: 'Studio Ghibli style', description: '자연스럽고 따뜻한 색감, 감성적 풍경 강조' },
        { id: 'manga_shinkai', label: 'Makoto Shinkai Style', prompt: 'Makoto Shinkai cinematic anime style', description: '섬세한 조명・광선・색그라데이션, 감성적 하늘빛 표현' },
        { id: 'manga_ufotable', label: 'Ufotable / Demon Slayer Style', prompt: 'Ufotable anime style, dynamic lighting, glowing outlines', description: '강한 명암, 불꽃・에너지 표현 뛰어남' },
        { id: 'manga_vagabond', label: 'Vagabond Ink Style', prompt: 'Vagabond manga ink style, sumi-e brush texture', description: '무협풍 먹선・붓터치, 사실적 근육・얼굴 묘사' },
    ],
    "카툰 / 웹툰 / 그래픽노블 스타일 (Cartoon / Webtoon / Graphic Novel Style)": [
        { id: 'cartoon_webtoon', label: 'Webtoon Style', prompt: 'webtoon-style illustration, Korean webtoon look', description: '컬러풀, 클린라인, 인물 중심 연출' },
        { id: 'cartoon_style', label: 'Cartoon Style', prompt: 'cartoon-style illustration', description: '단순화된 윤곽, 밝은 색조, 코믹한 느낌' },
        { id: 'cartoon_3d', label: '3D Cartoon Style', prompt: '3D cartoon style, Pixar-inspired CGI look', description: '픽사풍 입체감・빛 반사・표정 중심' },
        { id: 'cartoon_comicbook', label: 'Comic Book Style', prompt: 'comic book style, halftone shading', description: '서양 그래픽노블풍, 점묘・잉크톤 강조' },
        { id: 'cartoon_cel_shaded', label: 'Cel-Shaded Anime Style', prompt: 'cel-shaded anime style, toon shading', description: '게임・애니 렌더풍 (밝은 경계선, 음영 또렷)' },
        { id: 'cartoon_stylized', label: 'Stylized Illustration', prompt: 'stylized anime illustration, exaggerated proportions', description: '과장된 비율, 하이라이트・윤곽 강조' },
    ],
    "플래시 스타일 (Flash Style)": [
        { id: 'flash_2000s_style', label: '2000s Flash Animation', prompt: '2000s Flash animation style', description: '2000s Flash animation style' },
        { id: 'flash_early_web', label: 'Early Web Animation', prompt: 'early 2000s web animation', description: 'early 2000s web animation' },
        { id: 'flash_newgrounds', label: 'Newgrounds Style', prompt: 'Newgrounds style', description: 'Newgrounds style' },
        { id: 'flash_adobe', label: 'Adobe Flash Style', prompt: 'Adobe Flash style', description: 'Adobe Flash style' },
        { id: 'flash_vector', label: 'Vector Art', prompt: 'Vector art', description: 'Vector art' },
        { id: 'flash_cel', label: 'Cel Animation', prompt: 'cel animation', description: 'cel animation' },
        { id: 'flash_digital', label: 'Digital Art', prompt: 'digital art', description: 'digital art' },
        { id: 'flash_outlines', label: 'Bold Outlines', prompt: 'bold outlines', description: 'bold outlines' },
        { id: 'flash_colors', label: 'Flat Colors', prompt: 'flat colors', description: 'flat colors' },
        { id: 'flash_shading', label: 'Simple Shading', prompt: 'simple shading', description: 'simple shading' },
        { id: 'flash_internet_aesthetic', label: 'Early Internet Aesthetic', prompt: 'Early internet aesthetic', description: 'Early internet aesthetic' },
        { id: 'flash_low_res', label: 'Low Resolution', prompt: 'low resolution', description: 'low resolution' },
        { id: 'flash_pixelated', label: 'Slightly Pixelated', prompt: 'slightly pixelated', description: 'slightly pixelated' },
        { id: 'flash_retro_web', label: 'Retro Web Design', prompt: 'retro web design', description: 'retro web design' },
        { id: 'flash_bw', label: 'B&W Simple BG', prompt: 'black and white on a simple background', description: 'black and white on a simple background' },
        { id: 'flash_char_design', label: 'Simple Character', prompt: 'Simple character design', description: 'Simple character design' },
        { id: 'flash_expression', label: 'Exaggerated Expression', prompt: 'exaggerated expression', description: 'exaggerated expression' },
        { id: 'flash_comedic', label: 'Comedic', prompt: 'comedic', description: 'comedic' },
        { id: 'flash_goofy', label: 'Goofy', prompt: 'goofy', description: 'goofy' }
    ],
    "Genre / Theme (장르 / 테마)": [
        { id: 'genre_high_fantasy', label: '하이 판타지', prompt: 'High Fantasy theme', description: '하이 판타지' },
        { id: 'genre_dark_fantasy', label: '다크 판타지', prompt: 'Dark Fantasy theme', description: '다크 판타지' },
        { id: 'genre_steampunk', label: '스팀펑크', prompt: 'Steampunk theme', description: '스팀펑크' },
        { id: 'genre_arcanepunk', label: '아케인펑크 (마공학)', prompt: 'Arcanepunk theme', description: '아케인펑크' },
        { id: 'genre_cyberpunk', label: '사이버펑크', prompt: 'Cyberpunk theme', description: '사이버펑크' },
        { id: 'genre_solarpunk', label: '솔라펑크', prompt: 'Solarpunk theme', description: '솔라펑크' },
        { id: 'genre_biopunk', label: '바이오펑크', prompt: 'Biopunk theme', description: '바이오펑크' },
        { id: 'genre_cosmic_horror', label: '코스믹 호러', prompt: 'Cosmic Horror theme', description: '코스믹 호러' },
        { id: 'genre_space_opera', label: '스페이스 오페라', prompt: 'Space Opera theme', description: '스페이스 오페라' },
        { id: 'genre_gothic_romance', label: '고딕 로맨스', prompt: 'Gothic Romance theme', description: '고딕 로맨스' },
        { id: 'genre_lovecraftian', label: '러브크래프트 호러', prompt: 'Lovecraftian Horror theme', description: '러브크래프트 호러' },
        { id: 'genre_dieselpunk', label: '디젤펑크', prompt: 'Dieselpunk theme', description: '디젤펑크' },
        { id: 'genre_post_apocalyptic', label: '포스트 아포칼립스', prompt: 'Post-Apocalyptic theme', description: '포스트 아포칼립스' },
        { id: 'genre_noir_detective', label: '느와르 탐정', prompt: 'Noir Detective theme', description: '느와르 탐정' },
    ],
    "Environment / Background (환경 / 배경)": [
        { id: 'env_alien_jungle', label: '외계 정글', prompt: 'in an alien jungle with bioluminescent flora', description: '생체 발광 식물이 있는 외계 정글' },
        { id: 'env_submerged_ruins', label: '수중 유적', prompt: 'in the submerged ruins of a forgotten civilization', description: '잊혀진 문명의 물에 잠긴 폐허' },
        { id: 'env_sky_islands', label: '하늘섬', prompt: 'on floating sky islands connected by vines', description: '덩굴로 연결된 떠다니는 하늘 섬' },
        { id: 'env_mechanical_hive', label: '기계 벌집', prompt: 'inside a mechanical hive with intricate clockwork', description: '정교한 시계 장치가 있는 기계 벌집' },
        { id: 'env_crystal_caverns', label: '수정 동굴', prompt: 'in vast, unsettling crystal caverns', description: '광활하고 불안한 느낌의 수정 동굴' },
        { id: 'env_ruin_city', label: '폐허 도시', prompt: 'in a ruin city with empty street', description: '텅 빈 거리의 폐허 도시' },
    ],
    "Weather & Atmosphere (날씨 & 분위기)": [
        { id: 'weather_smog', label: '짙은 스모그', prompt: 'thick, unbreathable smog', description: '숨 막히는 짙은 스모그' },
        { id: 'weather_heat_haze', label: '이글거리는 아지랑이', prompt: 'shimmering heat haze', description: '아른거리는 아지랑이' },
        { id: 'weather_embers', label: '떠다니는 불씨', prompt: 'ethereal floating embers', description: '떠다니는 몽환적인 불씨' },
        { id: 'weather_cosmic_dust', label: '우주 먼지', prompt: 'swirling cosmic dust and nebulae', description: '소용돌이치는 우주 먼지와 성운' },
        { id: 'weather_magical_pollen', label: '마법의 꽃가루', prompt: 'magical pollen particles glimmering in the air', description: '공기 중에 반짝이는 마법 가루' },
        { id: 'weather_torrential_downpour', label: '폭우 / 장대비', prompt: 'in a torrential downpour', description: '장대비' },
    ],
    "Detail & Realism (디테일 & 사실성)": [
        { id: 'detail_insanely_detailed', label: '미친 디테일', prompt: 'insanely detailed', description: '극도로 세밀한 디테일' },
        { id: 'detail_hyperrealistic', label: '극사실주의', prompt: 'hyper-realistic', description: '극사실주의' },
        { id: 'detail_8k', label: '8K UHD 해상도', prompt: '8K UHD', description: '8K 초고화질' },
        { id: 'detail_cgi_vfx', label: 'CGI & VFX 효과', prompt: 'CGI, VFX', description: 'CGI 및 시각 효과' },
        { id: 'detail_intricate_details', label: '정교한 디테일', prompt: 'intricate details', description: '정교한 디테일' },
    ],
    "Texture & Shading (질감 & 쉐이딩)": [
        { id: 'texture_lifelike_skin_texture', label: '실감 나는 피부', prompt: 'lifelike skin texture', description: '실감 나는 피부 질감' },
        { id: 'texture_detailed_pores', label: '세밀한 모공', prompt: 'detailed pores', description: '세밀한 모공' },
        { id: 'texture_hyperrealistic_fur_texture', label: '극사실적 털 질감', prompt: 'hyperrealistic fur texture', description: '극사실적인 털 질감' },
        { id: 'texture_subsurface_scattering', label: '피부 빛 투과효과', prompt: 'subsurface scattering', description: '피부 밑으로 빛이 투과되는 효과' },
        { id: 'texture_ambient_occlusion', label: '앰비언트 오클루전', prompt: 'ambient occlusion', description: '물체 간의 가려진 부분에 생기는 그림자' },
    ],
    "Lighting & Time (조명 & 시간)": [
        { id: 'lighting_cinematic', label: '시네마틱 조명', prompt: 'cinematic lighting', description: '영화적 조명' },
        { id: 'lighting_dramatic_soft_lighting', label: '부드러운 드라마틱 조명', prompt: 'dramatic soft lighting', description: '드라마틱한 부드러운 조명' },
        { id: 'lighting_dramatic_rim_lighting', label: '윤곽 조명 (역광)', prompt: 'dramatic rim lighting', description: '드라마틱한 윤곽 조명' },
        { id: 'lighting_volumetric_lighting', label: '볼륨 조명 (빛줄기)', prompt: 'volumetric lighting', description: '빛줄기가 보이는 조명 (틴들 현상)' },
        { id: 'lighting_flickering_streetlights', label: '깜빡이는 가로등', prompt: 'flickering streetlights', description: '깜빡이는 가로등' },
        { id: 'lighting_golden_hour', label: '골든 아워 (황금빛)', prompt: 'golden hour lighting', description: '골든 아워 (일출/일몰)' },
        { id: 'lighting_blue_hour', label: '블루 아워 (푸른빛)', prompt: 'blue hour lighting', description: '블루 아워 (일출 전/일몰 후)' },
        { id: 'lighting_moonlight', label: '달빛', prompt: 'moonlight', description: '달빛' },
        { id: 'lighting_crepuscular_rays', label: '틈새 빛줄기', prompt: 'crepuscular rays', description: '틈새로 비치는 빛줄기' },
    ],
    "Shot & Composition (샷 & 구도)": [
        { id: 'comp_audience_pov', label: '관객 시점', prompt: 'shot from audience perspective, crowd silhouette in foreground, stage lighting', description: '관객석에서 무대를 바라보는 시점' },
        { id: 'comp_front_view', label: '정면 샷', prompt: 'front view, facing camera, symmetrical composition', description: '피사체를 정면에서 바라보는 구도' },
        { id: 'comp_low_angle_stage', label: '무대 로우 앵글', prompt: 'low angle shot from below stage, looking up at performer, dominating presence', description: '무대 아래에서 위로 올려다보는 웅장한 로우 앵글' },
        { id: 'comp_aerial_shot', label: '항공 샷 (드론)', prompt: 'aerial view, drone shot', description: '드론이나 항공기에서 촬영한 것처럼 아주 높은 상공에서 내려다보는 구도' },
        { id: 'comp_extreme_long_shot', label: '익스트림 롱 샷', prompt: 'extreme long shot', description: '광활한 배경 속 아주 작은 피사체' },
        { id: 'comp_long_shot', label: '롱 샷', prompt: 'long shot', description: '피사체의 전신과 주변 배경' },
        { id: 'comp_full_shot', label: '풀 샷', prompt: 'full shot', description: '피사체의 머리부터 발끝까지 화면에 꽉 차게 담는 샷' },
        { id: 'comp_medium_shot', label: '미디엄 샷', prompt: 'medium shot', description: '피사체의 상반신' },
        { id: 'comp_ots_shot', label: '어깨 걸고 찍기 (OTS)', prompt: 'over-the-shoulder shot', description: '한 인물의 어깨 너머로 다른 인물이나 대상을 바라보는 구도' },
        { id: 'comp_close_up_shot', label: '클로즈업', prompt: 'close-up shot', description: '피사체의 얼굴' },
        { id: 'comp_extreme_close_up', label: '익스트림 클로즈업', prompt: 'extreme close-up shot', description: '얼굴의 특정 부분(눈, 입 등)을 극단적으로 확대하여 감정을 강조' },
        { id: 'comp_pov_shot', label: '1인칭 시점 (POV)', prompt: 'Point of View shot (POV)', description: '주인공의 시점에서 바라보는 1인칭 시점 샷' },
        { id: 'comp_crane_shot', label: '크레인 샷', prompt: 'crane shot', description: '크레인을 사용하여 높은 위치에서 이동하며 촬영하는 듯한 역동적인 샷' },
        { id: 'comp_dutch_angle', label: '더치 앵글 (기울임)', prompt: 'dutch angle shot', description: '비스듬히 기울어진 앵글' },
        { id: 'comp_low_angle', label: '로우 앵글', prompt: 'low angle shot', description: '아래에서 위로 올려다보는 앵글' },
        { id: 'comp_worms_eye_view', label: '벌레 시점 (Worm\'s eye)', prompt: 'worm\'s-eye view', description: '바닥에 거의 붙어서 하늘을 향해 올려다보는 극단적인 로우 앵글' },
        { id: 'comp_high_angle', label: '하이 앵글', prompt: 'high angle shot', description: '위에서 아래로 내려다보는 앵글' },
        { id: 'comp_isometric_view', label: '쿼터뷰 (아이소메트릭)', prompt: 'Isometric view, quarter view', description: '45도 각도에서 비스듬히 내려다보는 시점. 게임, 건축, 인포그래픽 등에 자주 사용됩니다.' },
        { id: 'comp_top_down_view', label: '조감 시점 (Top-down)', prompt: 'Top-down view, bird\'s-eye view', description: '피사체를 90도 정면 위에서 수직으로 내려다보는 시점. 지도나 전략 게임 화면과 같은 구도입니다.' },
        { id: 'comp_shallow_dof', label: '얕은 심도 (아웃포커싱)', prompt: 'shallow depth of field', description: '얕은 심도 (배경 흐림)' },
        { id: 'comp_deep_dof', label: '깊은 심도 (팬 포커스)', prompt: 'deep depth of field', description: '깊은 심도 (전체 선명)' },
        { id: 'comp_motion_blur', label: '모션 블러', prompt: 'subtle motion blur', description: '미세한 모션 블러' },
        { id: 'comp_film_grain', label: '필름 그레인', prompt: 'subtle film grain', description: '미세한 필름 그레인' },
    ],
};

export const aspectRatioPromptKeys: CheatKey[] = [
    { id: 'ar_ultra_wide', label: '울트라 와이드', prompt: 'Ultra-wide angle shot', description: '울트라 와이드 앵글 샷' },
    { id: 'ar_anamorphic', label: '시네마스코프', prompt: 'Cinemascope, Anamorphic lens flare', description: '시네마스코프, 아나모픽 렌즈 플레어' },
    { id: 'ar_dark_angle', label: '다크 앵글', prompt: 'Dark angle, Ominous composition', description: '다크 앵글, 불길한 구도' },
    { id: 'ar_wide_angle', label: '어안 렌즈', prompt: 'Fisheyee lens perspective', description: '어안 렌즈 관점' },
    { id: 'ar_low_angle', label: '로우 앵글', prompt: 'Worm\'s-eye view, low angle shot', description: '벌레 시점, 로우 앵글 샷' },
    { id: 'ar_high_angle', label: '하이 앵글', prompt: 'Bird\'s-eye view, high angle shot', description: '조감도, 하이 앵글 샷' },
];
